### ISSUE TITLE
InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by 7ranceaddic7** [net-lisias-ksp/TweakScaleCompanion_KIS#4]
[LOG 09:44:25.769] [TweakScaleCompanion.KIS] Version 0.0.2.0 /L Beta
[EXC 09:44:25.771] InvalidOperationException: Sequence contains no elements
	System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
	TweakScaleCompanion.KIS.Startup.checkDependencies () (at <0295d416799a4395a7a7616445f28958>:0)
	TweakScaleCompanion.KIS.Startup.Start () (at <0295d416799a4395a7a7616445f28958>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Lisias** [comment]
Yeah, I had borked beautifully on this one. This idiot that type you this message decided it was a good idea to search for "TweakScale" instead of the programmatic name of the thing, "Scale".

See this commit for a good laugh: https://github.com/net-lisias-ksp/TweakScaleCompanion_KIS/commit/29f8ab5d155c74e68c0b8d95ca7bcc74800fc920

However... It's my understanding that the latest release has it fixed already.

What's version of the companion is on the KSP.log? This was an issue on 0.0.2.0, and I (hope) had if fixed on 0.0.2.1 , currently the latest.

**Comment by 7ranceaddic7** [comment]
Usually, pretty good about versioning with TS, but I must have missed that update. 

That is against TweakScaleCompanion_KIS v0.0.2.0, like you said.

I'll update in a few and run it again.

**Comment by Lisias** [comment]
I suggest to install KSP-AVC - just get rid of every MiniAVC and use that.

I could not live with the plethora of versions and forks I use on different KSP installments without this tool.

**Comment by 7ranceaddic7** [comment]
Back.  Yeah. that's got it.

I've avoided uninstalling MiniAVC because it's hooked into about 2 dozen mods and forces uninstalling.

![image](https://user-images.githubusercontent.com/4062616/93008682-38e32d80-f52c-11ea-9424-ab3de49fff3c.png)
ticking off Zero MiniAVC ...
![image](https://user-images.githubusercontent.com/4062616/93008688-544e3880-f52c-11ea-9d75-517a7cb19a72.png)
Ah well, time to do the deed.

**Comment by Lisias** [comment]
And that's yet one of the reasons I do not use CKAN on my installments - besides being practical.

Things just do not work as expected on real life. You must have a work around for when things goes out of control, as it's happening with you.

**Comment by Lisias** [comment]
On the bright side, this is going to be tackled down sooner or later.

https://github.com/KSP-CKAN/CKAN/issues/2490

**Comment by HebaruSan** [comment]
> I suggest to install KSP-AVC - just get rid of every MiniAVC and use that.

> I've avoided uninstalling MiniAVC because it's hooked into about 2 dozen mods and forces uninstalling.

You don't have MiniAVC installed via CKAN, you have **ZeroMiniAVC**, which exists to do exactly what Lisias suggested and deletes the MiniAVC plugins that are bundled in other mods. The two mods are basically opposites.

![image](https://user-images.githubusercontent.com/1559108/120570917-bc0c2280-c3de-11eb-832f-31cef8ce7fb9.png)

When MiniAVC started to crash people's installs due to an incompatible Unity upgrade, @linuxgurugamer decided to use ZeroMiniAVC as a workaround for those crashes by forcing it to be installed whenever his mods are installed. Then he released a version of MiniAVC that doesn't crash, and decided that ZeroMiniAVC would not delete the fixed version. It's a giant mess at this point before CKAN even gets involved. I would love to remove those fake dependencies on ZeroMiniAVC, but then I would have to fight @linuxgurugamer over it, and life is too short.

Uninstalling ZeroMiniAVC in CKAN will not do anything to help with the problems you've had here. It will just allow mods that you install later to run their MiniAVC components and show pop-ups when you start the game. So kind of the opposite.

KSP-CKAN/CKAN#2490 on the other hand might be useful, as it would restore the functionality that used to be available in ZeroMiniAVC of suppressing MiniAVC which has lately been eliminated.

**Comment by linuxgurugamer** [comment]
Go ahead and remove the dependency, I suppose that I'll just have to start reminding people to install it if they get weird problems

**Comment by linuxgurugamer** [comment]
I've also fixed the MiniAVC zip on Github
